config/routes.rb
Rails.application.routes.draw do
  resources :locations do
  	collection do
  		get 'search'
  	end
  end
  devise_for :users
  resources :games do
  resources :reviews
  end
  root 'games#index'

  resources :filters
end
# A resourceful route is declared in one line of code so you dont need to add index, destroy, edit and show routes

app/models/filter.rb
class Filter < ActiveRecord::Base
#filter has many games
  has_many :games

#validation for genres
validates :name, :presence => true
validates :name, :length => { :minimum => 4 }
validates :name, :uniqueness => { :message => "Already Been Used"}
end

app/models/game.rb
class Game < ActiveRecord::Base
#game belongs to a user
  belongs_to :user
#game belongs to a filter/genre
  belongs_to :filter
#games can have many reviews
  has_many :reviews

#image upload
  has_attached_file :game_img, styles: { game_index: "250x350>", game_show: "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :game_img, content_type: /\Aimage\/.*\z/
end

app/models/location.rb
class Location < ActiveRecord::Base
geocoded_by :address
after_validation :geocode, :if => :address_changed?
end

app/models/review.rb
class Review < ActiveRecord::Base
#Reviews belongs to a game
  belongs_to :game
#Reviews belongs to a user
  belongs_to :user

#validation for reviews
  validates :rating, :comment, :presence => true
  validates :comment, :length => {:minimum => 4 }
end

app/models/user.rb
class User < ActiveRecord::Base
#Users have many games
  has_many :games
#Users have many reviews
  has_many :reviews
#Users have many filters/genres
  has_many :filters

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
# Only users can add genres and edit and delete
before_action :authenticate_user!, only: [:new]
before_action :find_filter, only: [:show, :edit, :update, :destroy]

#show all genres in descending order
def index
  @filters = Filter.all.order("created_at DESC")
end

#This action links with current user
def new
 @filter = current_user.filters.build
end

#This action creates new filter and saves to the datbase
def create

@filter = current_user.filters.build(filter_params)
#If filter get saved it redirects to game page
if @filter.save
  redirect_to games_path(@game)
else
  render 'new'
end
end

def edit
end

#when edited the genre is updated
def update
  if @filter.update(filter_params)
    redirect_to filter_path(@filter)
  else
    render 'edit'
  end
end

#deletes genre
def destroy
  @filter.destroy
  redirect_to filters_path
end

private
#Defining filter parameters and permiting filter name
def filter_params
params.require(:filter).permit(:name, :game_id)
end

def find_filter
  @filter = Filter.find(params[:id])
end

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
# This function will take place before any of the functions
  before_action :find_game, only: [:show, :edit, :update, :destroy]
# Only users signed in can create new and edit games
  before_action :authenticate_user!, only: [:new, :edit]

#Displays all games in descending order
  def index
    if params[:filter].blank?
      @games = Game.all.order("created_at DESC")
    else
      @filter_id = Filter.find_by(name: params[:filter]).id
      @games = Game.where(:filter_id => @filter_id).order("created_at DESC")
    end
  end

#This function averages the ratings
  def show
    if @game.reviews.blank?
      @average_review = 0
    else
      @average_review = @game.reviews.average(:rating).round(2)
    end
  end

#Links to current user and show all filters
  def new
    @game = current_user.games.build
    @filters = Filter.all.map{ |c| [c.name, c.id] }
  end

#This action creates new game and shows and saves game to database
  def create
    @game = current_user.games.build(game_params)
    @game.filter_id = params[:filter_id]
    if @game.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @filters = Filter.all.map{ |c| [c.name, c.id] }
  end

#This action updates game
  def update
    @game.filter_id = params[:filter_id]
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

#This action deletes game
  def destroy
    @game.destroy
    redirect_to root_path
  end


  private
#Defining game parameters and permiting certain fields
    def game_params
      params.require(:game).permit(:name, :description, :developer, :filter_id, :game_img)
    end

#Find game by ID
    def find_game
      @game = Game.find(params[:id])
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

# get locations.json
def index
    @locations = Location.all
end

def search
    if params[:search].present?
      @location = params[:search]
      location = Geocoder.coordinates(params[:search])
      @latitude = location[0]
      @longitude = location[1]
  end
end

def show
end

# get locations new
def new
    @location = Location.new
end

# edit locations
def edit
end


#create new location and save
def create
  @location = Location.new(location_params)

  respond_to do |format|
    if @location.save
      format.html { redirect_to @location, notice: 'Location was successfully created.' }
      format.json { render :show, status: :created, location: @location }
    else
      format.html { render :new }
      format.json { render json: @location.errors, status: :unprocessable_entity }
    end
  end
end

#update new location
def update
  respond_to do |format|
    if @location.update(location_params)
      format.html { redirect_to @location, notice: 'Location was successfully updated.' }
      format.json { render :show, status: :ok, location: @location }
    else
      format.html { render :edit }
      format.json { render json: @location.errors, status: :unprocessable_entity }
    end
  end
end

#delete location
def destroy
  @location.destroy
  respond_to do |format|
    format.html { redirect_to locations_url, notice: 'Location was successfully deleted.' }
    format.json { head :no_content }
  end
end

private
# Use callbacks to share common setup or constraints between actions.
def set_location
    @location = Location.find(params[:id])
end


def location_params
    params.require(:location).permit(:address, :latitude, :longitude)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
# This function will take place before any of the functions
  before_action :find_game
  before_action :find_review, only: [:edit, :update, :destroy]
#Only users signed in can create new and edit review
  before_action :authenticate_user!, only: [:new, :edit]

#This action links to review
  def new
    @review = Review.new
  end

#This action creates new review and saves it
  def create
    @review = Review.new(review_params)
    @review.game_id = @game.id
    @review.user_id = current_user.id

    if @review.save
      redirect_to game_path(@game)
    else
      render 'new'
    end
  end

  def edit
  end

#This action updates the new review
  def update
    if @review.update(review_params)
      redirect_to game_path(@game)
    else
      render 'edit'
    end
  end

#This action deletes the review adn redirects to game page
  def destroy
    @review.destroy
    redirect_to game_path(@game)
  end

  private
#Defining review parameters and permiting rating and comment
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
#This action finds game by game ID
    def find_game
      @game = Game.find(params[:game_id])
    end
#This action finds review by review ID
    def find_review
      @review = Review.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/filters/edit.html.erb
<h1>Edit Genre</h1>
<!-- Form for genre -->
<%= simple_form_for @filter do |f| %>
<!-- validation for genres -->
<% if @filter.errors.any? %>
<ul>
 <% @filter.errors.full_messages.each do |message| %>
 <li>
   <%= message %>
  </li>
<% end %>
</ul>
<% end %>
<%= f.input :name, label: "Genre Name" %>
<%= f.button :submit %>
<% end %>

app/views/filters/index.html.erb
<% @filters.each do |filter| %>
<h3><%= link_to filter.name, filter_path(filter) %> </h3>
<% end %>

app/views/filters/new.html.erb
<h1>New Filter</h1>
<!-- Form for genre -->
<%= simple_form_for @filter do |f| %>
<!-- validation for genres -->
<% if @filter.errors.any? %>
<ul>
 <% @filter.errors.full_messages.each do |message| %>
 <li>
   <%= message %>
  </li>
<% end %>
</ul>
<% end %>
<%= f.input :name, label: "Genre Name" %>
<%= f.button :submit %>
<% end %>

app/views/filters/show.html.erb
<h3><%= @filter.name %></h3>

<!-- if user is signed in they can edit and delte -->
<% if user_signed_in? %>

  <% if @filter.user_id == current_user.id %>

    <%= link_to "Edit", edit_filter_path(@filter) %>
    <%= link_to "Delete", filter_path(@filter), method: :delete, data: { confirm: "Are You Sure?"} %>

  <% end %>

<% end %>

app/views/games/_form.html.erb
<!-- Game Form -->
<%= simple_form_for @game, :html => { :multipart => true } do |f| %>
  <%= select_tag(:filter_id, options_for_select(@filters), :prompt => "Select A Genre") %>
  <%= f.file_field :game_img %>
  <%= f.input :name, label: "Game Name" %>
  <%= f.input :description %>
  <%= f.input :developer %>
  <%= f.button :submit %>
<% end %>

app/views/games/edit.html.erb
<h1>Edit Game</h1>
<!-- Edit game form -->
<%= simple_form_for @game, :html => { :multipart => true } do |f| %>
  <%= f.select :filter_id, @filters %>
  <%= f.file_field :game_img %>
  <%= f.input :name, label: "Game Name" %>
  <%= f.input :description %>
  <%= f.input :developer %>
  <%= f.button :submit %>
<% end %>

app/views/games/index.html.erb
<h2 class="current-filter"><%= params[:filter] %></h2>
<!-- If there is no games in specific genre a message will show -->
<% if @games.count == 0 %>

  <h2>There Are No Games Currently In This Genre</h2>

<% else%>


<!-- If there is games a game image will show in selected genre -->
<% @games.each do |game| %>


        <a href="/games/<%= game.id %>">
          <%= image_tag game.game_img.url(:game_index) %>
        </a>


  <% end %>

<% end %>

app/views/games/new.html.erb
<h1>New Game</h1>
<!-- include form -->
<%= render 'form' %>

app/views/games/show.html.erb
<%= link_to "Back", root_path %>
<br><br>
<div class="row">
<div class="col-md-4">
<!-- Display game image -->
    <%= image_tag @game.game_img.url(:game_show) %>
</div>
<!-- Display game information -->
<div class="col-md-8">
  <h2><%= @game.name %></h2>
  <h3><%= @game.developer %></h3>
  <h4>Average Rating</h4>
<!-- Display average rating based on number of ratings -->
  <div class="average-review-rating" data-score=<%= @average_review %>></div>
  <span>According To <%= @game.reviews.count %> Reviews</span>
  <h4>Genre: <%= @game.filter.name %></h4>
  <p><%= @game.description %></p>
</div>
</div>

<div class="row">
  <hr>


  <div class="col-md-12">

<!-- Display reviews -->
  <h2>Reviews</h2>
    <%= render @game.reviews %>

    <div>
      <%= link_to "Add Review", new_game_review_path(@game) %>
    </div>

  </div>

</div>
<br>

<!-- if user is signed in they can edit and delte -->
<% if user_signed_in? %>

  <% if @game.user_id == current_user.id %>

    <%= link_to "Edit", edit_game_path(@game) %>
    <%= link_to "Delete", game_path(@game), method: :delete, data: { confirm: "Are You Sure?"} %>

  <% end %>

<% end %>
<!-- JQuery for rating feature -->
<script>
  $('.review-rating').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets'
  });
</script>

<script>
  $('.average-review-rating').raty({
    readOnly: true,
    path: '/assets/',
    score: function() {
      return $(this).attr('data-score')
    }
  });
</script>

app/views/genres/new.html.erb
<h1>New Genre</h1>

<%= simple_form_for @genre do |f| %>
<%= f.input :name, label: "Genre Name" %>
<%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assign2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- Navigation bar -->
  <nav class="navbar navbar-default">

    <div class="container">

      <div class="navbar-header">
        <%= link_to "Platinum Games", root_path, class: "navbar-brand" %>
      </div>

      <ul class="nav navbar-nav">
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log In", new_user_session_path %></li>
        <% end %>
      </ul>
<!-- Dropdown menu for genres -->
      <ul class="nav navbar-nav navbar-right">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Filter <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <% Filter.all.each do |filter| %>
            <li class="<%= 'active' if params[:filter] == filter.name %>">
              <%= link_to filter.name, games_path(filter: filter.name), class: "link" %>
            </li>
            <% end %>
          </ul>
        </li>
<!-- Display only if user is signed in -->
        <% if user_signed_in?%>
          <li><%= link_to "Add Game", new_game_path %></li>
          <li><%= link_to "Add Genre", new_filter_path %></li>
          <li><%= link_to "All Genres", filters_path %></li>
          <li><%= link_to "Store Location", locations_path %></li>
        <% end %>
      </ul>

    </div>

  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<div class="container">
<!-- Get all content -->
  <%= yield %>
</div>
</body>
</html>

app/views/locations/_form.html.erb
<%= simple_form_for(@location) do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :address %>
  <%= f.input :latitude %>
  <%= f.input :longitude %>
</div>

<div class="form-actions">
  <%= f.button :submit %>
</div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>
<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag search_locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<h1>Listing Locations</h1>

<table>
  <thead>
    <tr>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td><%= link_to 'Show', location %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %></td>
        <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path %>
<style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    text-align: left;
    padding: 8px;
}

tr:nth-child(even){background-color: #f2f2f2}

th {
    background-color: #4CAF50;
    color: white;
}</style>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/search.html.erb
<p id="notice"><%= notice %></p>

<%= form_tag search_locations_path, :method => :get do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search Near", :name => nil %>
  </p>
<% end %>

<p>
  <strong>Address:</strong>
  <%= @location %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@latitude}%2C#{@longitude}" %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@location.latitude}%2C#{@location.longitude}" %>

<h3>Nearby locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>

app/views/reviews/_form.html.erb
<!-- Form for reviews -->
<%= simple_form_for([@game, @game.reviews.build]) do |f| %>
<!-- Validation for reviews -->
  <% if @review.errors.any? %>
  <ul>
   <% @review.errors.full_messages.each do |message| %>
   <li>
     <%= message %>
    </li>
  <% end %>
  </ul>
  <% end %>

  <div id="rating-form">
    <label>Rating</label>
  </div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>


<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/_review.html.erb
<!-- Display review rating -->
<div class="review-rating" data-score="<%= review.rating %>"></div>
<p><%= review.comment %></p>
<!-- If user is signed in they can edit and delete reviews -->
<% if user_signed_in?%>

  <% if review.user_id == current_user.id %>

    <%= link_to "Edit", edit_game_review_path(review.game, review) %>
    <%= link_to "Delete", game_review_path(review.game, review), method: :delete, data: {confirm: "Are You Sure?" }%>

    <% end %>
<hr>
<% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<!-- Edit form for reviews -->
<%= simple_form_for([@game, @review]) do |f| %>
<div id="rating-form">
  <label>Rating</label>
</div>
  <%= f.input :comment %>
  <%= f.button :submit %>
<% end %>

<script>
  $('#rating-form').raty({
    path: '/assets/',
    scoreName: 'review[rating]'
  });
</script>

app/views/reviews/new.html.erb
<h1>New Review</h1>
<!-- Include form -->
<%= render 'form' %>